config/routes.rb
LBC::Application.routes.draw do
  get "users/index"
  get "users/show"
  get "users/edit"
  get "users/update"
  get "users/destroy"
  resources :annonces
  devise_for :users
  get "accueil/index"
  root 'accueil#index'

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  resourcify
  include Authority::Abilities
  belongs_to :author, class_name: 'User'

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
 
  rolify
  include Authority::UserAbilities
  has_many :posts, foreign_key: :author_id

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
  end
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    @annonces = Annonce.all
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @annonce = Annonce.new(annonce_params.merge(author: current_user))

    respond_to do |format|
      if @annonce.save
        format.html { redirect_to @annonce, notice: 'Annonce was successfully created.' }
        format.json { render action: 'show', status: :created, location: @annonce }
      else
        format.html { render action: 'new' }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    respond_to do |format|
      if @annonce.update(annonce_params)
        format.html { redirect_to @annonce, notice: 'Annonce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    respond_to do |format|
      format.html { redirect_to annonces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params.require(:annonce).permit(:numero, :titre, :description, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_in){ |u| u.permit(:email, :password) }
     devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:nom, :prenom, :promo,  :email, :password, :password_confirmation)}
     devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:nom, :prenom, :promo, :email, :password, :password_confirmation, :current_password) }
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_version
  "3.1.1"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accueil/index.html.haml
.jumbotron
	%h1
		Bienvenue
	%p
		Sur LeBonCoin de l'ENSIIE, des gens vendent des trucs

app/views/annonces/_form.html.haml
= form_for @annonce do |f|
  - if @annonce.errors.any?
    #error_explanation
      %h2= "#{pluralize(@annonce.errors.count, "error")} prohibited this annonce from being saved:"
      %ul
        - @annonce.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :titre
    = f.text_field :titre
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/annonces/edit.html.haml
%h1 Editing annonce

= render 'form'

= link_to 'Show', @annonce
\|
= link_to 'Back', annonces_path

app/views/annonces/index.html.haml
%h1 Liste des annonces

%table
  %tr
    %th Titre
    %th Description
    %th Image
    %th
    %th
    %th

  - @annonces.each do |annonce|
    %tr
      %td= annonce.titre
      %td= annonce.description
      %td= annonce.image
      %td= link_to 'Show', annonce
      %td= link_to 'Edit', edit_annonce_path(annonce)
      %td= link_to 'Destroy', annonce, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Nouvelle Annonce', new_annonce_path

app/views/annonces/new.html.haml
%h1 New annonce

= render 'form'

= link_to 'Back', annonces_path

app/views/annonces/show.html.haml
%p#notice= notice

%p
  %b Titre:
  = @annonce.titre
%p
  %b Description:
  = @annonce.description
%p
  %b Image:
  = @annonce.image

= link_to 'Edit', edit_annonce_path(@annonce)
\|
= link_to 'Back', annonces_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeBonCoin de l'ENSIIE</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/accueil/index">LeBonCoin de l'ENSIIE</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/accueil/index">Accueil</a></li>
          <li><a href="/annonces">Annonces</a></li>
          <li><a href="/users/index">Membres</a></li>
          <li><a href="#">A propos</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        </ul>
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container">

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      Petons
    </div>
  </footer>

  <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>

</body>
</html>

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/index.html.haml
%h1 Liste des membres

%table
  %tr
    %th Nom
    %th Prenom
    %th Promo
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.nom
      %td= user.prenom
      %td= user.promo
      %td= user.email
      %td= link_to 'Show', "/users/show"
      %td= link_to 'Edit', "/users/edit"
      -# %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Nom:
  = @user.nom
%p
  %b Prenom:
  = @user.prenom
%p
  %b Promo:
  = @user.promo

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml